paths:
  /experience/{experience_id}:
    get:
      tags:
        - Experience
      summary: Get an experience by ID
      description: Returns an experience by ID
      parameters:
        - name: Accept-Language
          in: header
          required: true
          schema:
            type: string
            enum: [en, fr]
            default: en
          description: Language code for localized responses (default is "en")
        - name: experience_id
          in: path
          required: true
          schema:
            type: number
          description: Experience ID
          example: 1
      responses:
        '200':
          description: A single experience
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    example: 1
                  experience_category_id:
                    type: number
                    example: 1
                  country_id:
                    type: number
                    example: 1
                  title:
                    type: string
                    example: "Italian Pasta Making Workshop"
                  description:
                    type: string
                    example: "Learn how to make authentic Italian pasta from scratch with a professional chef. Take home your creations and impress your friends and family!"
                  duration:
                    type: number
                    example: 1
                  banner_url:
                    type: string
                    nullable: true
                    example: null
                  rating:
                    type: number
                    nullable: true
                    example: null
                  review_count:
                    type: number
                    nullable: true
                    example: null
                  features:
                    type: string
                    nullable: true
                    example: null
                  duration_type:
                    type: string
                    example: "1"
                  language:
                    type: string
                    example: "1"
                  status:
                    type: string
                    example: "1"
                  country:
                    type: object
                    properties:
                      id:
                        type: number
                        example: 1
                      name:
                        type: string
                        example: "Afghanistan"
                  experience_category:
                    type: object
                    properties:
                      id:
                        type: number
                        example: 1
                      name:
                        type: string
                        example: "Food & Drink"
                      status:
                        type: string
                        example: "1"
                  experience_price:
                    type: object
                    properties:
                      id:
                        type: number
                        example: 1
                      experience_id:
                        type: number
                        example: 1
                      min_guests:
                        type: number
                        example: 1
                      max_guests:
                        type: number
                        example: 10
                      price:
                        type: number
                        example: 10
                      service_fee:
                        type: number
                        example: 0
                      price_type:
                        type: string
                        example: "1"
                      currency:
                        type: string
                        example: "1"
                  experience_schedules:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                          example: 1
                        experience_id:
                          type: number
                          example: 1
                        available_date:
                          type: string
                          format: date-time
                          example: "2022-12-31T18:30:00.000Z"
                        available_time:
                          type: string
                          example: "09:00:00"
                        min_guests:
                          type: number
                          example: 1
                        max_guests:
                          type: number
                          example: 10
                        status:
                          type: string
                          example: "1"
                  experience_hosts:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                          example: 1
                        user_id:
                          type: number
                          example: 2
                        experience_id:
                          type: number
                          example: 1
                        user:
                          type: object
                          properties:
                            id:
                              type: number
                              example: 2
                            first_name:
                              type: string
                              example: "Oasis"
                            last_name:
                              type: string
                              example: "Admin"
                            email:
                              type: string
                              example: "host@yopmail.com"
                            profile_url:
                              type: string
                              nullable: true
                              example: null
                            role:
                              type: string
                              example: "2"
        '500':
          description: Internal server error fetching experience
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Failed to fetch experience
  /experience:
    get:
      tags:
        - Experience
      summary: Get a list of experiences
      description: Returns a list of experiences filtered by category and country.
      parameters:
        - name: Accept-Language
          in: header
          required: true
          schema:
            type: string
            enum: [en, fr]
            default: en
          description: Language code for localized responses (default is "en")
        - name: experience_category_id
          in: query
          required: false
          schema:
            type: number
          description: Filter experiences by category ID
          example: 1
        - name: country_id
          in: query
          required: false
          schema:
            type: number
          description: Filter experiences by country ID
          example: 1
        - name: min_price
          in: query
          required: false
          schema:
            type: number
          description: Filter experiences by minimum price
          example: 1
        - name: max_price
          in: query
          required: false
          schema:
            type: number
          description: Filter experiences by maximum price
          example: 100
        - name: rating
          in: query
          required: false
          schema:
            type: number
          description: Filter experiences by rating
          example: 4
      responses:
        '200':
          description: A list of filtered experiences
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                      example: 1
                    experience_category_id:
                      type: number
                      example: 1
                    country_id:
                      type: number
                      example: 1
                    title:
                      type: string
                      example: "Italian Pasta Making Workshop"
                    description:
                      type: string
                      example: "Learn how to make authentic Italian pasta from scratch with a professional chef. Take home your creations and impress your friends and family!"
                    duration:
                      type: number
                      example: 1
                    banner_url:
                      type: string
                      nullable: true
                      example: null
                    rating:
                      type: number
                      nullable: true
                      example: null
                    review_count:
                      type: number
                      nullable: true
                      example: null
                    features:
                      type: string
                      nullable: true
                      example: null
                    duration_type:
                      type: string
                      example: "1"
                    language:
                      type: string
                      example: "1"
                    status:
                      type: string
                      example: "1"
                    country:
                      type: object
                      properties:
                        id:
                          type: number
                          example: 1
                        name:
                          type: string
                          example: "Afghanistan"
                    experience_category:
                      type: object
                      properties:
                        id:
                          type: number
                          example: 1
                        name:
                          type: string
                          example: "Food & Drink"
                        status:
                          type: string
                          example: "1"
                    experience_price:
                      type: object
                      properties:
                        id:
                          type: number
                          example: 1
                        experience_id:
                          type: number
                          example: 1
                        min_guests:
                          type: number
                          example: 1
                        max_guests:
                          type: number
                          example: 10
                        price:
                          type: number
                          example: 10
                        service_fee:
                          type: number
                          example: 0
                        price_type:
                          type: string
                          example: "1"
                        currency:
                          type: string
                          example: "1"
                    experience_schedules:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: number
                            example: 1
                          experience_id:
                            type: number
                            example: 1
                          available_date:
                            type: string
                            format: date-time
                            example: "2022-12-31T18:30:00.000Z"
                          available_time:
                            type: string
                            example: "09:00:00"
                          min_guests:
                            type: number
                            example: 1
                          max_guests:
                            type: number
                            example: 10
                          status:
                            type: string
                            example: "1"
                    experience_hosts:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: number
                            example: 1
                          user_id:
                            type: number
                            example: 2
                          experience_id:
                            type: number
                            example: 1
                          user:
                            type: object
                            properties:
                              id:
                                type: number
                                example: 2
                              first_name:
                                type: string
                                example: "Oasis"
                              last_name:
                                type: string
                                example: "Admin"
                              email:
                                type: string
                                example: "host@yopmail.com"
                              profile_url:
                                type: string
                                nullable: true
                                example: null
                              role:
                                type: string
                                example: "2"
        '500':
          description: Internal server error fetching experiences
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Failed to fetch experience list
